import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/Provider";

export const metadata: Metadata = {
  title: "AI agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider>
        <body> {children} </body>
      </ThemeProvider>
    </html>
  );
}
